;KODLAMA SABLONU

	list		p=16f877A	; hangi pic
	#include	<p16f877A.inc>	; SFR register 'lar?n tan?mland??? kutuphane
	
	__CONFIG H'3F31'

; WDT, ossilatör gibi register ayarlar?

	
;KULLANILACAK DEGISKENLER

GECIKME1	EQU	0x20    ;GEC?KME 1. DONGU
GECIKME2	EQU	0x21    ;GECIKME 2. DONGU
GECIKME3	EQU	0x22    ;GECIKME 3.DONGU
BAS_B		EQU	0x23
BAS_C		EQU	0x24
ORTA_B		EQU	0x25
ORTA_C		EQU	0x26
SON_B		EQU	0x27
SON_C		EQU	0x28
BAS_YON		EQU	0x29



;********************************************************************************************
	ORG     0x000             	; Baslama vektoru

	nop			  			  	; ICD ozelliginin aktif edilmesi icin gereken bekleme 
  	goto    BASLA              	; baslama etiketine gir

	
;**********************************************************************************************
	ORG     0x004             	; kesme vektoru

	
;***********************************************************************************************

GECIKME				; (herbir komut 4mhz de 1mikrosn) = 1 sn GEC?KME (yakla??k)
	MOVLW	0x08
	MOVWF	GECIKME1	; Bu gecikme degiskeni eger daha uzun süreler laz?m olursa kullan?lacak bu ornekte 1 kez yeterli 
	MOVLW	0x9F
	MOVWF	GECIKME2
	MOVLW	0x01
	MOVWF	GECIKME3
DONGU1
	DECFSZ	GECIKME1,1
	GOTO	$+2
	DECFSZ	GECIKME2,1
	GOTO	$+2
	DECFSZ	GECIKME3,1
	GOTO	DONGU1
		
	RETURN
	
GECIK			; (herbir komut 4mhz de 1mikrosn) = 1 sn GEC?KME (yakla??k)
	MOVLW	0xE7
	MOVWF	GECIKME1
	MOVLW	0x04
	MOVWF	GECIKME2
DONGU
	DECFSZ	GECIKME1,1
	GOTO	$+2
	DECFSZ	GECIKME2, 1
	GOTO	DONGU
	
	RETURN
	
AYARLAR
	BANKSEL	TRISB
	CLRF	TRISB
	CLRF	TRISC
	MOVLW	0x06
	MOVWF	ADCON1
	MOVLW	B'00001111'
	MOVWF	TRISA
	BANKSEL	PORTA
	MOVLW	B'00011100'
	MOVWF	PORTB
	MOVLW	B'00000100'
	MOVWF	PORTC
	MOVLW	D'2'
	MOVWF	BAS_B
	MOVWF	BAS_C
	MOVWF	ORTA_C
	MOVWF	SON_C
	MOVLW	D'3'
	MOVWF	ORTA_B
	MOVLW	D'4'
	MOVWF	SON_B
	MOVLW	0x01
	MOVWF	BAS_YON
	RETURN
	
LOOKUP_TABLE
	ADDWF	PCL,1
	RETLW	B'00000001'
	RETLW	B'00000010'
	RETLW	B'00000100'
	RETLW	B'00001000'
	RETLW	B'00010000'
	RETLW	B'00100000'
	RETLW	B'01000000'
	

KONTROL
	BTFSS	PORTA,0
	GOTO	YUKARI
	BTFSS	PORTA,1
	GOTO	ASAGI
	BTFSS	PORTA,2
	GOTO	SAGA
	BTFSS	PORTA,3
	GOTO	SOLA
	GOTO	KONTROL
	
	
BASLA
	
	CALL	AYARLAR
	GOTO	KONTROL
	
YEDEKLEME
	MOVF	ORTA_B,0
	MOVWF	SON_B
	MOVF	ORTA_C,0
	MOVWF	SON_C
	MOVF	BAS_B,0
	MOVWF	ORTA_B
	MOVF	BAS_C,0
	MOVWF	ORTA_C
	RETURN	
	
SUPURME
	
	MOVF	BAS_B,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTB
	MOVF	BAS_C,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTC
	CALL	GECIK
	
	MOVF	ORTA_B,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTB
	MOVF	ORTA_C,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTC
	CALL	GECIK
	
	MOVF	SON_B,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTB
	MOVF	SON_C,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTC
	CALL	GECIK
	
	
	
	BTFSS	PORTA,0
	GOTO	YUKARI
	BTFSS	PORTA,1
	GOTO	ASAGI
	BTFSS	PORTA,2
	GOTO	SAGA
	BTFSS	PORTA,3
	GOTO	SOLA
	
	GOTO	SUPURME
	

YUKARI
	BTFSS	BAS_YON,1
	GOTO	$+2
	GOTO	SUPURME
	MOVLW	0x01
	MOVWF	BAS_YON
	CALL	GECIKME
	CALL	YEDEKLEME
	MOVF	BAS_B,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTB
	BTFSS	PORTB,0
	GOTO	$+4
	MOVLW	0x06
	MOVWF	BAS_B
	GOTO	SUPURME
	DECF	BAS_B,1
	GOTO	SUPURME


ASAGI
	BTFSS	BAS_YON,0
	GOTO	$+2
	GOTO	SUPURME
	MOVLW	0x02
	MOVWF	BAS_YON
	CALL	GECIKME
	CALL	YEDEKLEME
	MOVF	BAS_B,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTB
	BTFSS	PORTB,6
	GOTO	$+3
	CLRF	BAS_B
	GOTO	SUPURME
	INCF	BAS_B,1
	GOTO	SUPURME

	
SAGA
	BTFSS	BAS_YON,3
	GOTO	$+2
	GOTO	SUPURME
	MOVLW	0x04
	MOVWF	BAS_YON
	CALL	GECIKME
	CALL	YEDEKLEME
	MOVF	BAS_C,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTC
	BTFSS	PORTC,4
	GOTO	$+3
	CLRF	BAS_C
	GOTO	SUPURME
	INCF	BAS_C,1
	GOTO	SUPURME
	
SOLA
	BTFSS	BAS_YON,2
	GOTO	$+2
	GOTO	SUPURME
	MOVLW	0x08
	MOVWF	BAS_YON
	CALL	GECIKME
	CALL	YEDEKLEME
	MOVF	BAS_C,0
	CALL	LOOKUP_TABLE
	MOVWF	PORTC
	BTFSS	PORTC,0
	GOTO	$+4
	MOVLW	0x04
	MOVWF	BAS_C
	GOTO	SUPURME
	DECF	BAS_C,1
	GOTO	SUPURME
	END                       ; Program sonu


